#!/usr/bin/env bash
# Configures an Ubuntu server:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

grep -v localhost /etc/hosts | grep -v facebook.com > /tmp/newhosts
echo "127.0.0.2 localhost" >> /tmp/newhosts
echo "8.8.8.8 facebook.com" >> /tmp/newhosts
cp /tmp/newhosts /etc/hosts
